export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_FAILED='FETCH_FAILED';
export const PURCHASE_BURGER='PURCHASE_BURGER';
export const PURCHASE_FAILED='PURCHASE_FAILED';
export const PURCHASE_START='PURCHASE_START';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDER_START='FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDERS_FAILED='FETCH_ORDERS_FAILED;'

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';

export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT='SET_AUTH_REDIRECT';